services:
  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - TZ=Europe/Madrid
    volumes:
      - nodered_data:/data
      - ./flujos_node-red_idc.json:/data/flows.json
    restart: always
    
volumes:
  nodered_data:
